sudo: required

language: java

jdk:
    - oraclejdk8

install:
  - git clone https://github.com/zalando-incubator/zally.git

  # Build a local zally server
  - cd zally
  - gradle build

  # Build zally CLI
  - cd cli
  - gradle build
  - gradle bin --info
  - cd ..

  # Launch local zally server
  - echo "spring.profiles.active=dev" > application.properties
  - gradle bootRun > /dev/null &
  - sleep 10

script:
  - cd cli
  - cp build/libs/zally.jar bin/
  - bin/zally ../../swagger/zally-test.json
